name: TCR Spec Suite

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"

    steps:
      - uses: actions/checkout@v2

      - name: Initial setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec

  testall:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Test (matrix)
    needs: [test]
    steps:
      - name: Check status of all test runs
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
